name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install nbdev
      run: |
        python -m pip install --upgrade pip
        pip install nbdev==2.3.12
    - uses: fastai/workflows/nbdev-ci@2.3.12
